openapi: 3.2.0
info:
  title: api-keys configurations API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: api-keys configurations
paths:
  /api/v1/api-keys/configs/{tenantId}:
    get:
      tags:
      - api-keys configurations
      summary: Get API key configuration
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiKeysConfig'
          description: API keys configuration.
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          headers:
            retry-after:
              schema:
                $ref: '#/components/schemas/RetryAfterHeader'
          description: Request has been rate limited.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Unexpected error.
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
          format: uid
          example: Hj5p89bylz1r2AUC6joLNuHzVx5Ya8cF
        required: true
        description: The tenant ID from which you wish to retrieve the API key configuration.
      description: Retrieves the API key configuration for a tenant.
      operationId: getApiKeysConfiguration
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
    patch:
      tags:
      - api-keys configurations
      summary: Update API keys configuration
      responses:
        '204':
          description: API keys configuration updated successfully.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Invalid request was made.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Requestor not allowed to update the API keys configuration.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Failed to update the API keys configuration.
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          headers:
            retry-after:
              schema:
                $ref: '#/components/schemas/RetryAfterHeader'
          description: Request has been rate limited.
      parameters:
      - in: path
        name: tenantId
        schema:
          type: string
          format: uid
        required: true
        description: The tenant ID of the API keys configuration to be retrieved.
      description: Updates the API keys configuration for a given tenant ID.
      operationId: updateApiKeyConfiguration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiKeysConfigPatchSchema'
        required: true
        description: Configurations that the user wants to update for API keys.
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
components:
  schemas:
    RetryAfterHeader:
      type: object
      properties:
        retry-after:
          type: integer
          description: The amount of seconds to wait before retrying the request.
    Error:
      type: object
      required:
      - code
      - title
      properties:
        code:
          type: string
          description: The error code.
        meta:
          type: object
          description: Additional properties relating to the error.
        title:
          type: string
          description: Summary of the problem.
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        source:
          type: object
          properties:
            pointer:
              type: string
              description: A JSON Pointer to the property that caused the error.
            parameter:
              type: string
              description: The URI query parameter that caused the error.
          description: References to the source of the error.
        status:
          type: integer
          description: The HTTP status code.
      description: An error object.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: List of errors and their properties.
    ApiKeysConfig:
      type: object
      properties:
        max_keys_per_user:
          type: number
          default: 5
          maximum: 1000
          minimum: 0
          description: The maximum number of active API keys that any user can create for the specified tenant.
        max_api_key_expiry:
          type: string
          default: PT24H
          example: PT24H
          description: The maximum lifetime, in ISO8601 duration format, for which an API key can be issued for the specified tenant, e.g. `P7D` for 7 days.
        scim_externalClient_expiry:
          type: string
          default: P365D
          example: P365D
          description: The expiry of the scim `externalClient` token in ISO8601 duration format, e.g. `P365D` for 365 days. Used during the creation of an `externalClient` API key for configuring a SCIM compatible Identity Provider.
    ApiKeysConfigPatchSchema:
      type: array
      items:
        $ref: '#/components/schemas/ApiKeyConfigPatch'
      example:
      - op: replace
        path: /max_keys_per_user
        value: 10
    ApiKeyConfigPatch:
      type: object
      required:
      - op
      - path
      - value
      properties:
        op:
          enum:
          - replace
          type: string
          description: The operation to be performed.
        path:
          enum:
          - /max_api_key_expiry
          - /max_keys_per_user
          - /scim_externalClient_expiry
          type: string
          description: The path for the given resource field to patch.
        value:
          description: The value to be used for this operation.
      description: A JSON Patch document as defined in https://datatracker.ietf.org/doc/html/rfc6902.
