openapi: 3.2.0
info:
  title: reports Status API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: Status
paths:
  /api/v1/reports/{id}/status:
    get:
      tags:
      - Status
      summary: Get report request processing status
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportStatus'
          description: Returns the request processing status.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-400000
                  title: Bad or malformed request
                  detail: ''
          description: Bad request. Malformed syntax, errors in params.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-401000
                  title: Forbidden
                  detail: ''
          description: Unauthorized, JWT invalid or not provided.
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-403000
                  title: Forbidden
                  detail: ''
          description: Forbidden, user did not authenticate.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-404000
                  title: url path not found
                  detail: ''
          description: Not found.
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-409000
                  title: Conflict
                  detail: ''
          description: Conflicted request. Report aborted.
        '429':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: HTTP-429
                  title: Too Many Requests
                  detail: The user has sent too frequent requests which resulted in an undesired response code ("error rate limiting")
          description: Too many request. Indicates the user has sent too many requests in a given amount of time, aka "rate limiting".
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                - code: REP-500000
                  title: Internal server error
                  detail: ''
          description: Internal server error.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          example: 01562a37-23e3-4b43-865d-84c26122276c
        required: true
        description: Identifier of the request.
      operationId: getStatus
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
components:
  schemas:
    MetaExportError:
      properties:
        appErrors:
          $ref: '#/components/schemas/AppErrors'
        selectionErrors:
          $ref: '#/components/schemas/SelectionErrors'
      description: Define the export error metadata. Each property is filled if it is related to the export error type.
    AppError:
      properties:
        appId:
          type: string
          example: 11ecf638-0be4-4b94-a9e6-91218f34e175
          description: app id
        method:
          type: string
          example: GetObject
          description: The method that is failing.
        parameters:
          type: object
          description: Parameters of method that fails.
          additionalProperties:
            type: string
      description: Error in resource handling
    SelectionErrors:
      type: array
      items:
        $ref: '#/components/schemas/SelectionError'
      description: Errors occurring in selections.
    ExportErrors:
      type: array
      items:
        $ref: '#/components/schemas/ExportError'
      description: Errors occured during report generation.
    Float64:
      type: number
      format: float64
      x-go-type:
        type: Float64
        import:
          alias: cModels
          package: github.com/qlik-trial/reporting-service/v10/pkg/models
    SelectionError:
      properties:
        detail:
          type: string
          description: Details about the field selection error.
        errorType:
          enum:
          - fieldMissing
          - fieldValuesMissing
          - stateMissing
          - groupStateGroupMissing
          - groupStateGroupNotApplicable
          - groupStateFieldDefMissing
          type: string
        fieldName:
          type: string
          example: Year
          description: The field name that is missing.
        stateName:
          type: string
          description: The state name that is missing.
        missingValues:
          type: array
          items:
            $ref: '#/components/schemas/QFieldValue'
        isFieldNameMissing:
          type: boolean
          example: false
          description: Deprecated, use errorType instead. True if the fieldName is missing. The missingValues array is empty in this case
          x-qlik-deprecated: true
      description: Selection error related to a fieldName. The field name is missing or some of his selection values are missing or a state is missing
    ReportStatus:
      type: object
      example:
        status: done
        results:
        - location: https://qlikcloud.com:443/api/v1/temp-contents/619baab68023910001efcb86?inline=1
          outputId: output1
        statusLocation: /reports/01562a37-23e3-4b43-865d-84c26122276c/status
        resolutionAttempts: 1
      required:
      - status
      properties:
        status:
          enum:
          - queued
          - processing
          - done
          - failed
          - aborted
          - visiting
          - aborting
          type: string
          example: processing
          description: Status of the requested report.
        reasons:
          type: array
          items:
            $ref: '#/components/schemas/Reason'
          deprecated: true
          description: Present when status is failed. Deprecated. Use /reports/{id}/outputs instead.
          x-qlik-deprecated: true
        results:
          type: array
          items:
            $ref: '#/components/schemas/Result'
          deprecated: true
          description: Present when the status is "done". Deprecated. Use /reports/{id}/outputs instead.
          x-qlik-deprecated: true
        requestErrors:
          $ref: '#/components/schemas/ExportErrors'
        statusLocation:
          type: string
          format: uri
          example: /reports/c86132d2-109e-47c5-bccc-83c5d3a40185/status
          description: Relative path to status location.
        resolutionAttempts:
          type: integer
          format: int32
          example: 2
          description: Count how many times the resolution of this report was attempted.
    Error:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ExportErrors'
    ExportError:
      type: object
      required:
      - code
      - title
      properties:
        code:
          type: string
          description: "The unique code for the error\n\n- \"REP-400000\" Bad request. The server could not understand the request due to invalid syntax.\n- \"REP-400008\" Selections error.\n- \"REP-400009\" Maximum 16384 columns limit exceeded. Download data in a visualization can't generate an .xlsx file due to limitations to the number of columns you can download.\n- \"REP-400010\" Maximum 1048566 rows limit exceeded. Download data in a visualization can't generate an .xlsx file due to limitations to the number of rows you can download.\n- \"REP-400011\" The size of the downloaded Excel file exceed 100 MB limit. Download data in a visualization can't generate an .xlsx file due to limitations to the amount of data you can download.\n- \"REP-400015\" Bad request in enigma request. The patch value has invalid JSON format.\n- \"REP-400017\" Static App size exceeded.\n- \"REP-400018\" Excel string length exceeded.\n- \"REP-400020\" Invalid Issuer.\n- \"REP-400024\" Cannot extract claims from JWT.\n- \"REP-400028\" Invalid Tags.\n- \"REP-400029\" Reload Entitlement Limit Reached.\n- \"REP-400035\" Multiple selections detected in a field having OneAndOnlyone attribute.\n- \"REP-400036\" No selection detected in a field having OneAndOnlyone attribute.\n- \"REP-400037\" Max number of images exceeded in a report.\n- \"REP-400038\" Max number of nested levels exceeded in report.\n- \"REP-400039\" Max number of objects exceeded in a report.\n- \"REP-400040\" Max number of templates exceeded in a report.\n- \"REP-400041\" Unsupported dimension type for level tag.\n- \"REP-400050\" Error retrieving outputs.\n- \"REP-400052\" Report Request Aborted from internal error.\n- \"REP-400054\" The number of generated cycle reports exceeds the maximum allowed.\n- \"REP-400055\" Export options not allowed for this object.\n- \"REP-400057\" The sense object has an empty GenericType.\n- \"REP-400102\" Image rendering invalid strategy error on Sense client.\n- \"REP-400240\" Engine Client Global generic closure error\n- \"REP-400260\" Engine Client generic closure error.\n- \"REP-400280\" Engine Client proxy generic closure error.\n- \"REP-401000\" Unauthorized. The client must authenticate itself to get the requested response.\n- \"REP-401001\" Unauthorized, bad JWT.\n- \"REP-403000\" Forbidden. The client does not have access rights to the content.\n- \"REP-403001\" App forbidden, the user does not have read permission on the app.\n- \"REP-403002\" Chart type not supported.\n- \"REP-403019\" Export is not available for app with enabled directQuery feature.\n- \"REP-403025\" No entitlement to perform the operation.\n- \"REP-403026\" No entitlement to perform the operation. Export capability is off.\n- \"REP-403027\" Object without Hypercube or unsupported object type.\n- \"REP-403048\" Forbidden. User does not have permission to export the report (access control usePermission)\n- \"REP-404000\" Not found. The server can not find the requested resource.\n- \"REP-404001\" App not found, the app does not exist or it has been deleted.\n- \"REP-404002\" Chart not found, the chart does not exist or it has been deleted.\n- \"REP-404003\" Sheet not found, the sheet does not exist or it has been deleted or it is unavailable.\n- \"REP-404004\" Story not found, the story does not exist or it has been deleted or it is unavailable.\n- \"REP-409001\" App conflict.\n- \"REP-409021\" Reload timestamp constraint not met.\n- \"REP-409046\" Report aborted due to app reload.\n- \"REP-422030\" Apply variables error.\n- \"REP-422051\" There is no report to produce due to empty dataset or missing fields (the measure/dimension was removed or omitted in Section Access)\n- \"REP-429000\" Too many request. The user has sent too many requests in a given amount of time (\"rate limiting\").\n- \"REP-429012\" Exceeded max session tenant quota. A tenant has opened too many different sessions at the same time.\n- \"REP-429014\" The export could not be completed within the requested deadline.\n- \"REP-429016\" Exceeded max session tenant quota per day.\n- \"REP-429022\" Enigma generic abort.\n- \"REP-400064\" Missing Bookmark \n- \"REP-500000\" Fail to resolve resource.\n- \"REP-500006\" Fail to get report session parameters.\n- \"REP-500014\" The app did not open within 10 minutes.\n- \"REP-500023\" Validate Report Request Tags failure.\n- \"REP-500045\" Failure setting Bookmark timestamp.\n- \"REP-500047\" Error setting GroupState.\n- \"REP-500053\" Unexpected number of generated cycle reports.\n- \"REP-500059\" The App is corrupt.\n- \"REP-500061\" Engine Memory limit reached.\n- \"REP-500062\" Too many resolution attempts for a task.\n- \"REP-500063\" Engine terminated\n- \"REP-500100\" Image rendering generic error on Sense client.\n- \"REP-500101\" Image rendering could not set cookies error on Sense client.\n- \"REP-500103\" Image rendering JS timeout error on Sense client.\n- \"REP-500104\" Image rendering load URL timeout error on Sense client.\n- \"REP-500105\" Image rendering max paint attempts exceeded error on Sense client.\n- \"REP-500106\" Image rendering max JS attempts exceeded error on Sense client.\n- \"REP-500107\" Image rendering render timeout error on Sense client.\n- \"REP-500108\" Image rendering JS failure due to timeout error on Sense client.\n- \"REP-500109\" Image rendering generic JS failure error on Sense client.\n- \"REP-500200\" Report Generator error.\n- \"REP-500240\" Engine Global generic closure error.\n- \"REP-500260\" Engine Websocket generic closure error.\n- \"REP-500280\" Engine proxy generic closure error.\n- \"REP-503001\" Rest Engine Error.\n- \"REP-503005\" Engine unavailable, qix-sessions error no engines available.\n- \"REP-503013\" Session unavailable. The engine session used to create the report is unavailable.\n- \"REP-503060\" Engine Service unavailable.\n"
        meta:
          $ref: '#/components/schemas/MetaExportError'
        title:
          type: string
          description: A summary in english explaining what went wrong.
        detail:
          type: string
          description: Optional. MAY be used to provide more concrete details.
      description: Error occured during report generation.
    Result:
      type: object
      required:
      - outputId
      - location
      properties:
        location:
          type: string
          format: uri
          example: https://t.eu.qlikcloud.com:443/api/v1/temp-contents/619b77be498fea00018de0e1?inline=1
          description: Location to download the generated report.
        outputId:
          type: string
          example: output1
          description: The output identifier which uniquely identifies an output (PDF, image etc.) within the same request.
        exportErrors:
          $ref: '#/components/schemas/ExportErrors'
      description: Result and info about the generated report.
    QFieldValue:
      properties:
        text:
          type: string
          example: '2021'
          description: String value of the field value.
        number:
          $ref: '#/components/schemas/Float64'
        isNumeric:
          type: boolean
          example: true
          x-nullable: true
          description: IsNumeric tells whether the field value is text or number. Default value is equal to defaultIsNumeric property in QSelection.
      description: In order to apply a selection just one of text/number needs to be set, this must be associated with the correct isNumeric bool. In some scenarios both text and number may be set.
    Reason:
      properties:
        traceId:
          type: string
          example: '00000000000000000000000000000000'
        outputId:
          type: string
          example: output1
          description: The output identifier which uniquely identifies an output (PDF, image etc.) within the same request.
        exportErrors:
          $ref: '#/components/schemas/ExportErrors'
    AppErrors:
      type: array
      items:
        $ref: '#/components/schemas/AppError'
      description: Errors occurring when dealing with the app.
