openapi: 3.2.0
info:
  title: ml Aliases API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: Aliases
paths:
  /api/v1/ml/deployments/{deploymentId}/aliases:
    get:
      tags:
      - Aliases
      summary: List aliases
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AliasFindResponse'
          description: '`OK`'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalError'
        '502':
          $ref: '#/components/responses/502BadGateway'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/FailureDefault'
      parameters:
      - $ref: '#/components/parameters/aliasesFilter'
      - $ref: '#/components/parameters/aliasesSort'
      - $ref: '#/components/parameters/limit'
      - $ref: '#/components/parameters/offset'
      - $ref: '#/components/parameters/deploymentId'
      description: Retrieves a list of aliases based on filter parameters for a deployment.
      operationId: getAliases
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
    post:
      tags:
      - Aliases
      summary: Create an alias
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AliasPostResponse'
          description: '`Created`'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalError'
        '502':
          $ref: '#/components/responses/502BadGateway'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/FailureDefault'
      parameters:
      - $ref: '#/components/parameters/deploymentId'
      description: Creates an alias for a deployment.
      operationId: postAlias
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AliasInput'
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
  /api/v1/ml/deployments/{deploymentId}/aliases/{aliasId}:
    get:
      tags:
      - Aliases
      summary: Get an alias
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AliasGetResponse'
          description: '`OK`'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalError'
        '502':
          $ref: '#/components/responses/502BadGateway'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/FailureDefault'
      parameters:
      - $ref: '#/components/parameters/deploymentId'
      - $ref: '#/components/parameters/aliasId'
      description: Retrieves an alias that exists on the deployment.
      operationId: getAlias
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
    patch:
      tags:
      - Aliases
      summary: Update an alias
      responses:
        '204':
          $ref: '#/components/responses/204NoContent'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalError'
        '502':
          $ref: '#/components/responses/502BadGateway'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/FailureDefault'
      parameters:
      - $ref: '#/components/parameters/deploymentId'
      - $ref: '#/components/parameters/aliasId'
      description: Updates an alias for a deployment.
      operationId: updateAliases
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AliasPatch'
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
    delete:
      tags:
      - Aliases
      summary: Delete an alias
      responses:
        '204':
          $ref: '#/components/responses/204NoContent'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500InternalError'
        '502':
          $ref: '#/components/responses/502BadGateway'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
        default:
          $ref: '#/components/responses/FailureDefault'
      parameters:
      - $ref: '#/components/parameters/deploymentId'
      - $ref: '#/components/parameters/aliasId'
      description: Delete an alias from a deployment.
      operationId: deleteAlias
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
components:
  responses:
    502BadGateway:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Bad Gateway`'
    500InternalError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Internal Error`'
    401Unauthorized:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Unauthorized`'
    404NotFound:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Not Found`'
    403Forbidden:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Forbidden`'
    503ServiceUnavailable:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Service Unavailable`'
    204NoContent:
      description: '`No Content`'
    FailureDefault:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Unexpected Error`'
    400BadRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Failure'
      description: '`Bad Request`'
  schemas:
    AliasPostResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            id:
              $ref: '#/components/schemas/EntityId'
            type:
              enum:
              - alias
              type: string
            attributes:
              $ref: '#/components/schemas/Alias'
          additionalProperties: false
      additionalProperties: false
    DeploymentId:
      type: string
      format: uuid
      description: ID of a model deployment
      x-qlik-fiterable: true
    ResponseLinks:
      type: object
      required:
      - first
      - prev
      - self
      - next
      - last
      properties:
        last:
          type: object
          properties:
            href:
              type: string
              format: uri
              description: 'Link to the last set of responses from `limit` minus `offset` to

                `limit`

                '
        next:
          type: object
          properties:
            href:
              type: string
              format: uri
              description: 'Link to the next set of responses

                '
        prev:
          type: object
          properties:
            href:
              type: string
              format: uri
              description: 'Link to the previous set of responses

                '
        self:
          type: object
          properties:
            href:
              type: string
              format: uri
              description: 'Link to the current set of responses

                '
        first:
          type: object
          properties:
            href:
              type: string
              format: uri
              description: 'Link to the first set of responses from `offset` 0 to count `limit``

                '
      description: Resource links included in paginated responses
      additionalProperties: false
    AliasGetResponse:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          required:
          - type
          - id
          - attributes
          properties:
            id:
              $ref: '#/components/schemas/EntityId'
            type:
              enum:
              - alias
              type: string
            attributes:
              $ref: '#/components/schemas/Alias'
          additionalProperties: false
      additionalProperties: false
    UpdatedAt:
      type: string
      description: Timestamp when this was updated
    AliasFindResponse:
      type: object
      required:
      - data
      - links
      properties:
        data:
          type: array
          items:
            type: object
            required:
            - type
            - id
            - attributes
            properties:
              id:
                $ref: '#/components/schemas/EntityId'
              type:
                enum:
                - alias
                type: string
              attributes:
                $ref: '#/components/schemas/Alias'
            additionalProperties: false
        meta:
          $ref: '#/components/schemas/FindResponseMeta'
        links:
          $ref: '#/components/schemas/ResponseLinks'
      additionalProperties: false
    AliasPatch:
      type: array
      items:
        $ref: '#/components/schemas/AliasPatchItem'
      example:
      - op: replace
        path: /name
        value: New Name
      - op: replace
        path: /models
        value: modelId
    Alias:
      type: object
      required:
      - id
      - name
      - createdAt
      - updatedAt
      - createdBy
      - deploymentId
      - models
      - mode
      properties:
        id:
          $ref: '#/components/schemas/EntityId'
        mode:
          $ref: '#/components/schemas/AliasMode'
        name:
          $ref: '#/components/schemas/EntityName'
        models:
          $ref: '#/components/schemas/ModelsInfo'
        createdAt:
          $ref: '#/components/schemas/CreatedAt'
        createdBy:
          type: string
          description: ID of the owner/user that created this entity
        updatedAt:
          $ref: '#/components/schemas/UpdatedAt'
        deploymentId:
          $ref: '#/components/schemas/DeploymentId'
      description: An AutoML alias
    CreatedAt:
      type: string
      description: Timestamp when this was created
    AnyType:
      description: Use for fields that can be `any` type (string, number, etc.)
    EnumSortAliases:
      enum:
      - name
      - +name
      - -name
      type: string
    Failure:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/APIError'
          uniqueItems: true
        traceId:
          type: string
      additionalProperties: false
    FindResponseMeta:
      type: object
      required:
      - count
      properties:
        count:
          type: integer
      description: Meta for FIND operations
      additionalProperties: false
    EntityName:
      type: string
      description: Name of this entity
      x-qlik-filterable: true
    EntityId:
      type: string
      format: uuid
      description: ID of this entity
      x-qlik-filterable: true
    APIError:
      type: object
      required:
      - code
      - title
      properties:
        code:
          type: string
          description: Qlik error code (not HTTP response status code)
        meta:
          type: object
          properties:
            issue:
              type: string
              description: The issue code
            details:
              type: string
              description: Extra details for what may have caused the error
            errorId:
              type: string
              description: The unique id of the error instance
            argument:
              type: string
              description: The argument
            resource:
              type: string
              description: The resource type that the error occurred on
            resourceId:
              type: string
              description: The resource id that the error occurred on
          description: 'Additional details about the error. These may vary by error.

            '
          additionalProperties: false
        title:
          type: string
          description: Short summary of error
        detail:
          type: string
          description: Description of the error
      description: An error object
      additionalProperties: false
    AliasInput:
      type: object
      required:
      - data
      properties:
        data:
          type: object
          required:
          - type
          - attributes
          properties:
            type:
              enum:
              - alias
              type: string
              default: alias
            attributes:
              type: object
              required:
              - name
              - models
              properties:
                name:
                  $ref: '#/components/schemas/EntityName'
                models:
                  $ref: '#/components/schemas/ModelsInfo'
              additionalProperties: false
          additionalProperties: false
      description: 'Input for creating a new alias

        '
      additionalProperties: false
    AliasMode:
      enum:
      - default
      - undefined
      type: string
      description: The mode of an alias. Default mode means the model assigned to that alias will be used if alias is not specified
    ModelInfo:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/EntityId'
      description: Model information stored on an alias
      additionalProperties: false
    AliasPatchItem:
      type: object
      required:
      - op
      - path
      - value
      properties:
        op:
          enum:
          - replace
          type: string
          description: All patch requests use the replace operation
        path:
          enum:
          - /name
          - /models
          type: string
          description: Path for the property you want to update
        value:
          $ref: '#/components/schemas/AnyType'
      description: Alias values that can be patched.
      additionalProperties: false
    ModelsInfo:
      type: array
      items:
        $ref: '#/components/schemas/ModelInfo'
  parameters:
    aliasesSort:
      in: query
      name: sort
      style: form
      schema:
        $ref: '#/components/schemas/EnumSortAliases'
      example: sort=field1,+field2,-field3,...
      required: false
      description: 'Field(s) by which to sort response

        '
    limit:
      in: query
      name: limit
      schema:
        type: integer
        default: 32
        maximum: 100
      example: 10
      required: false
      description: Number of results per page. Default is 32.
    aliasId:
      in: path
      name: aliasId
      schema:
        type: string
      required: true
      description: ID of the alias
    aliasesFilter:
      in: query
      name: filter
      schema:
        type: string
      example: '`filter=modelId eq "UUID" and mode eq "Default"`'
      required: false
      description: 'Alias fields by which you can filter responses

        - `name` string - Aliases with exact name

        - `modelId` UUID string - By model ID

        - `mode` enum string - Mode by which alias is set to

        '
    deploymentId:
      in: path
      name: deploymentId
      schema:
        type: string
      required: true
      description: ID of the deployment
    offset:
      in: query
      name: offset
      schema:
        type: integer
      example: 32
      required: false
      description: Number of rows to skip before getting page[size]
