openapi: 3.2.0
info:
  title: Login API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: Login
paths:
  /login:
    get:
      tags:
      - Login
      summary: Login using interactive identity provider
      responses:
        '302':
          content:
            text/html:
              schema:
                type: string
          headers:
            Location:
              schema:
                type: string
          description: Redirect to the identity provider.
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Invalid login.
      parameters:
      - in: query
        name: login_hint
        schema:
          type: string
        example: user@qlik.com
        required: false
        description: Hint to the Authorization Server about the login identifier the End-User might use to log in.
      - in: query
        name: max_age
        schema:
          type: number
          example: 3600
        required: false
        description: 'Specifies the allowable elapsed time in seconds since the last time the End-User was actively authenticated by the OpenID Provider.

          If time is greater than max_age, force user to re-authorize.

          '
      - in: query
        name: prompt
        schema:
          enum:
          - none
          - login
          type: string
        required: false
        description: Specifies whether the Authorization Server prompts the End-User for re-authentication and consent.
      - in: query
        name: returnto
        schema:
          type: string
        example: automations/editor/fef1ba5f-facb-4cd1-9c69-8ddc6c61b7e3
        required: false
        description: Relative or full URL on the tenant to redirect to after successful login.
      - in: query
        name: scope
        style: spaceDelimited
        schema:
          enum:
          - offline_access
          type: array
          example: offline_access
        explode: false
        required: false
        description: Specifies the scope of access for login. Only supports offline_access to request a refresh token from the identity provider.
      - in: header
        name: Qlik-Web-Integration-ID
        schema:
          type: string
        example: OG_YzbL1zweMS4XQcv88J_n0853IbM0R
        required: false
        description: Web Integration ID associated with origin whitelist used to validate returnto value.
      description: Initiates login using the active interactive identity provider associated with the tenant. Uses default Qlik identity provider if no customer-configured interactive identity provider is active.
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
      operationId: getLogin
      x-operation-id-source: derived
components:
  schemas:
    Error:
      type: object
      required:
      - code
      - title
      properties:
        code:
          type: string
          description: The error code.
        meta:
          type: object
          description: Non-standard information about the error.
        title:
          type: string
          description: The error title.
        detail:
          type: string
          description: The detailed error message.
        status:
          type: string
          description: The http status code.
      description: An error object.
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          description: List of errors and their properties.
      description: A representation of the errors encountered from the HTTP request.
