openapi: 3.2.0
info:
  title: sharing-tasks sharing tasks executions API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: sharing tasks executions
paths:
  /api/v1/sharing-tasks/{taskId}/executions:
    get:
      tags:
      - sharing tasks executions
      summary: List sharing task executions
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharingExecutionListResponse'
          description: The sharing-executions list has been successfully returned.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad request, malformed syntax or errors in parameters.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Task or execution not found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      parameters:
      - in: path
        name: taskId
        schema:
          type: string
        required: true
        description: The sharing task identifier.
      - in: query
        name: limit
        schema:
          type: integer
          default: 20
          maximum: 200
          minimum: 1
        required: false
        description: Limit the returned result set
      - in: query
        name: next
        schema:
          type: string
        required: false
        description: The cursor to the next page of data. Only one of next or previous may be specified.
      - in: query
        name: offset
        schema:
          type: integer
          default: 0
          minimum: 0
        required: false
        description: Offset for pagination - how many elements to skip
      - in: query
        name: prev
        schema:
          type: string
        required: false
        description: The cursor to the previous page of data. Only one of next or previous may be specified.
      - in: query
        name: sort
        schema:
          type: array
          items:
            enum:
            - starttime
            - -starttime
            - +starttime
            type: string
        required: false
        description: Sort the returned result set by the specified field
      - in: query
        name: status
        schema:
          enum:
          - successful
          - failed
          type: string
        required: false
        description: Specifies a filter for a particular field and value of an execution
      description: Lists executions for the specified sharing task.
      operationId: SharingExecutionsList
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
  /api/v1/sharing-tasks/{taskId}/executions/{executionId}:
    get:
      tags:
      - sharing tasks executions
      summary: Get sharing task execution
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharingExecutionResponse'
          description: The execution has been successfully returned.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: The specified task or execution ID is invalid (e.g. not a number).
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Task or execution not found.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      parameters:
      - in: path
        name: executionId
        schema:
          type: string
        required: true
        description: The execution identifier. If value is "latest", the latest execution will be returned
      - in: path
        name: taskId
        schema:
          type: string
        required: true
        description: The sharing task identifier.
      - in: query
        name: status
        schema:
          enum:
          - successful
          - failed
          - cancelled
          type: string
        required: false
        description: Filter by status. If not present then no filtering is done on the status. This is only relevant when requesting latest execution.
      description: Retrieves a specific sharing task execution.
      operationId: sharingExecutionsIDGet
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
  /api/v1/sharing-tasks/{taskId}/executions/{executionId}/files/{fileAlias}:
    get:
      tags:
      - sharing tasks executions
      summary: Get sharing task execution file
      responses:
        '200':
          content:
            image/png:
              schema:
                type: string
                format: binary
            application/json:
              schema:
                type: string
                format: binary
          description: The content of the file has been successfully returned.
        '404':
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/Errors'
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: A task or execution with the specified ID was not found.
        '500':
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/Errors'
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            image/png:
              schema:
                $ref: '#/components/schemas/Errors'
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      parameters:
      - in: path
        name: executionId
        schema:
          type: string
        required: true
        description: The execution identifier.
      - in: path
        name: fileAlias
        schema:
          type: string
        required: true
        description: The execution identifier. If value is "latest", the latest execution will be returned
      - in: path
        name: taskId
        schema:
          type: string
        required: true
        description: The sharing task identifier.
      - in: query
        name: status
        schema:
          enum:
          - successful
          - failed
          - cancelled
          type: string
        required: false
        description: Filter by status. If not present then no filtering is done on the status. This is only relevant when requesting latest execution.
      description: Retrieves the file content for the requested execution and file type.
      operationId: sharingExecutionsFilesAliasGet
      x-qlik-stability: stable
      x-qlik-visibility: public
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
components:
  schemas:
    ListLinks:
      type: object
      properties:
        next:
          $ref: '#/components/schemas/Page'
        prev:
          $ref: '#/components/schemas/Page'
        self:
          $ref: '#/components/schemas/Self'
    Self:
      type: object
      properties:
        href:
          type: string
          example: http://localhost:8787/v1/items/5da5825325dc9a0dd0260af9
      description: Object with Href to a particular element or set of elements
    StandardListResponseProps:
      type: object
      required:
      - currentPageCount
      - totalCount
      properties:
        totalCount:
          type: integer
          description: total count of entries in the collection as a whole
        currentPageCount:
          type: integer
          description: count of entries on the currently shown page
      description: properties that should be added to every list response
    SharingExecutionPersist:
      type: object
      properties:
        id:
          type: string
          readOnly: true
          description: Gets the execution identifier.
          x-go-custom-tag: bson:"_id"
        appId:
          type: string
          readOnly: true
          description: appId associated to sharing task execution
        files:
          type: array
          items:
            $ref: '#/components/schemas/SharingExecutionFile'
          readOnly: true
        errors:
          $ref: '#/components/schemas/SharingExecutionErrors'
        status:
          enum:
          - initialized
          - in-progress
          - successful
          - failed
          - cancelled
          - invalid
          - presuccessful
          - cancelling
          type: string
          readOnly: true
          description: Status of the task execution
        endTime:
          type: string
          readOnly: true
          description: Timestamp of execution successful stop
        eventID:
          type: string
          readOnly: true
          description: eventID of the trigger NATS event
        ownerId:
          type: string
          readOnly: true
          description: Owner of the execution
        reloadId:
          type: string
          readOnly: true
          description: If this execution was triggered by an app reload. This will contain the reloadId from reloads service. Otherwise it is empty or omitted.
        tenantId:
          type: string
          readOnly: true
          description: The tenant that this execution belongs to
        eventTime:
          type: string
          readOnly: true
          description: eventTime of the trigger NATS event
        startTime:
          type: string
          readOnly: true
          description: Timestamp of execution start
        bookmarkId:
          type: string
          readOnly: true
          description: The ID of a filter in a reporting request
          x-qlik-deprecated: true
        failedTime:
          type: string
          readOnly: true
          description: Timestamp of execution stop
        reloadTime:
          type: string
          readOnly: true
          description: If this execution was triggered by an app reload. This will contain the reload time to compare with reporting service when the report is requested.
        targetUser:
          $ref: '#/components/schemas/TargetUser'
        totalCount:
          type: integer
          readOnly: true
          description: Total count of reports in this execution
        workflowID:
          type: string
          readOnly: true
          description: Workflow that the execution belongs to. Note that in a multi-recipient context we can have multiple executions (one per recipient) that share the same unique workflow.
        bookmarkIds:
          type: array
          items:
            type: string
            description: The ID of a filter in a reporting request
          readOnly: true
        failedCount:
          type: integer
          readOnly: true
          description: Total count of failed reports in this execution
        successCount:
          type: integer
          readOnly: true
          description: Total count of successfully generated reports in this execution
        cancelledTime:
          type: string
          readOnly: true
          description: Timestamp of execution cancel
        sharingTaskID:
          type: string
          readOnly: true
          description: ID for the sharing task that this execution references
        cancelledCount:
          type: integer
          readOnly: true
          description: Total count of cancelled reports in this execution
        totalUploadCount:
          type: integer
          readOnly: true
          description: Total count of reports to be uploaded in this execution
        failedUploadCount:
          type: integer
          readOnly: true
          description: Total count of failed uploaded reports in this execution
        successUploadCount:
          type: integer
          readOnly: true
          description: Total count of successfully uploaded reports in this execution
    TargetUser:
      type: object
      properties:
        type:
          type: string
          description: type of user eg email, userId, groupId
        value:
          type: string
          description: contains the value of user type e.g. abc@xyz.com, 213efewr3
        timezone:
          type: string
          description: timezone for the timestamp on the attached file name
        filterName:
          type: string
          x-qlik-deprecated: true
        filterNames:
          type: array
          items:
            type: string
            description: contains the value of the user filter
      description: User that this execution is targeting as a recipient
    Page:
      type: object
      properties:
        href:
          type: string
          example: http://localhost:8787/v1/items?limit=12
          description: URL to particular set of elements
        type:
          enum:
          - prev
          - next
          type: string
          example: next
          description: Page type, can be next or prev
        token:
          type: string
          example: JwAAAAJfaWQAGQAAADVjZjUwM2NjMjVkYzlhMTM1MzYwZTVjZAAA
          description: Page unique token
    SharingExecutionErrors:
      type: array
      items:
        $ref: '#/components/schemas/SharingExecutionError'
    Error_meta:
      type: object
      properties:
        httpCode:
          type: integer
          readOnly: true
          description: HTTP error code.
    Links:
      type: object
      properties:
        self:
          $ref: '#/components/schemas/Self'
    SharingExecutionFile:
      type: object
      properties:
        type:
          enum:
          - image
          - pdf
          - pptx
          - xlsx
          - html
          - docx
          type: string
        fileID:
          type: string
          example: za1b2c3d4z
        userId:
          type: string
          readOnly: true
          description: userId associated with the file
        fileAlias:
          type: string
          example: small-image
        templateId:
          type: string
          format: uuid
          readOnly: true
          description: identify the source task template
        tempContentsLocation:
          type: string
    SharingExecutionError:
      type: object
      properties:
        code:
          type: string
          readOnly: true
          description: Error code specific to sharing service.
        title:
          type: string
          readOnly: true
          description: Error title.
        detail:
          type: string
          readOnly: true
          description: Error cause.
    SharingExecutionListResponse:
      allOf:
      - $ref: '#/components/schemas/StandardListResponseProps'
      - type: object
        properties:
          links:
            $ref: '#/components/schemas/ListLinks'
          executions:
            type: array
            items:
              $ref: '#/components/schemas/SharingExecutionResponse'
            description: Gets a list of sharing-executions.
    Errors:
      type: object
      example:
        errors:
        - code: HTTP-123
          title: short error message
          details: detailed error message
        traceId: 7975401f3954aa47
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        traceId:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
          readOnly: true
          description: Error code specific to sharing service.
        meta:
          $ref: '#/components/schemas/Error_meta'
        title:
          type: string
          readOnly: true
          description: Error title.
        detail:
          type: string
          readOnly: true
          description: Error cause.
    SharingExecutionResponse:
      allOf:
      - $ref: '#/components/schemas/SharingExecutionPersist'
      - type: object
        properties:
          links:
            $ref: '#/components/schemas/Links'
          fileLocations:
            type: array
            items:
              type: string
