openapi: 3.2.0
info:
  title: conditions condition preview API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: condition preview
paths:
  /api/v1/conditions/previews:
    post:
      tags:
      - condition preview
      summary: Create condition preview request\
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreviewResponse'
          description: Condition preview request created.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response.
      description: Create condition preview request.
      operationId: conditionsPreview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConditionCreateRequest'
        description: Create condition preview request
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
  /api/v1/conditions/previews/{id}:
    get:
      tags:
      - condition preview
      summary: Get condition preview response
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PreviewStatusResponse'
          description: The evaluation
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Bad request body
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Resource does not exist.
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error response.
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uid
        required: true
        description: The id of the condition
      description: Get condition preview response.
      operationId: conditionsPreviewGet
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
components:
  schemas:
    PreviewStatusResponse:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/Errors'
        status:
          enum:
          - ACCEPTED
          - FAILED
          - RUNNING
          - SUCCESSFUL
          type: string
          readOnly: true
        condition:
          $ref: '#/components/schemas/Condition'
        previewId:
          type: string
          format: uid
          example: 467ea9bc-bbd7-11ea-b3de-0242ac130004
          readOnly: true
          description: When the resource was created
        evaluation:
          $ref: '#/components/schemas/PreviewEvaluation'
    ConditionMeasures:
      type: array
      items:
        $ref: '#/components/schemas/ConditionMeasures_inner'
      description: List of returned measures
    Selections:
      type: array
      items:
        $ref: '#/components/schemas/Selections_inner'
      description: List of fields according to the bookmark definition
    CompoundCondition_data:
      type: object
      properties:
        history:
          $ref: '#/components/schemas/HistoryProperties'
        conditions:
          type: array
          items:
            type: string
          example:
          - rDDAcMEI1V0qzauEWepEVY8oSLJ9fvA2
          - qFPF1dAtPK4vfPTmKyyuKaqA6iERCwLi
          - 4gnz8E6ZruG0lkSKwkau66P24CtORyLr
          - ATs--Z0b_NGyuHajcbQkxu7RrajgPaEQ
          description: Array of condition ids
        expression:
          type: string
          example: ($0 OR $1) AND ($2 OR $3)
          description: Boolean expression made up of variable names defined from the conditions section
      description: Condition data
    ConditionBase:
      type: object
      properties:
        id:
          type: string
          format: uid
          example: 5f31c6e8476ae50001030fb6
          readOnly: true
          description: The unique id for the resource
        type:
          enum:
          - compound
          - data
          type: string
          example: compound
          description: Indicates the condition type
        appId:
          type: string
          example: 4xQ1chLoHkOikyzUGcHJquteNrAfketW
          description: The id of the app the condition is evaluated against
        created:
          type: string
          format: string
          example: 2006-01-02T15:04:05Z07:00
          readOnly: true
          description: When the resource was created
        ownerId:
          type: string
          format: uid
          example: EIwSIgqjmbHGwQJI0ShQoS3ORdz5nCpA
          readOnly: true
          description: The id of the user the user which owns the condition
        updated:
          type: string
          format: string
          example: 2006-01-02T14:04:05Z07:00
          readOnly: true
          description: When the resource was last updated
        tenantId:
          type: string
          format: uid
          example: 5GI7yWoJk9lvNtuEc66SXCypXVfhbVeH
          readOnly: true
          description: The tenant id
        bookmarkId:
          type: string
          example: anTjnOABmxlCirVx8IRfhWhLd9IZjENl
          description: The bookmark corresponding to the selection state to apply to the app at evaluation time
        createdById:
          type: string
          format: uid
          example: EIwSIgqjmbHGwQJI0ShQoS3ORdz5nCpA
          readOnly: true
          description: The id of the user which created the condition
        description:
          type: string
          example: My condition
          description: Description of the condition
        lastReloadTime:
          type: string
          format: RFC3339
          example: 2006-01-02T15:04:05Z07:00
          readOnly: true
          description: The time of the last reload, if the scan is triggered by a reload. If exists and value does not match app's last reload time, the evaluation will fail.
      description: A base condition
    SingleErrorResponse:
      type: object
      properties:
        code:
          type: string
          readOnly: true
          description: Error code specific to condition manager.
        meta:
          type: object
          properties: {}
          description: meta properties for an error.
        title:
          type: string
          readOnly: true
          description: Error title.
        detail:
          type: string
          readOnly: true
          description: Error cause.
    PreviewResponse:
      type: object
      properties:
        previewId:
          type: string
          format: uid
          example: 467ea9bc-bbd7-11ea-b3de-0242ac130004
          readOnly: true
          description: When the resource was created
    PreviewEvaluation:
      type: object
      properties:
        endTime:
          type: string
          format: string
          readOnly: true
          description: The time the evaluation ended
        ownerId:
          type: string
          format: uid
          readOnly: true
          description: userId of user being impersonated to evaluate the condition
        tenantId:
          type: string
          format: uid
          readOnly: true
          description: The tenant id
        resultUrl:
          type: string
          description: URL to download the condition results
        startTime:
          type: string
          format: string
          readOnly: true
          description: The time the evaluation started
    ErrorResponse:
      type: object
      example:
        errors:
        - code: HTTP-123
          title: short error message
          details: detailed error message
        traceId: 7975401f3954aa47
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/SingleErrorResponse'
          description: Array of errors
        traceId:
          type: string
          example: d6dba97c917e3f3d77c82f40f37c9d85
          description: trace id
    ConditionDimensions:
      type: array
      items:
        $ref: '#/components/schemas/ConditionDimensions_inner'
      description: List of returned dimensions
    Errors:
      type: array
      items:
        $ref: '#/components/schemas/Error'
    HistoryProperties:
      type: object
      properties:
        enabled:
          type: boolean
          example: true
          description: Is history enabled
      description: History properties
    Condition:
      type: object
      required:
      - type
      properties:
        type:
          enum:
          - compound
          - data
          type: string
          example: compound
          description: Indicates the condition type
        ownerId:
          type: string
          format: uid
          example: EIwSIgqjmbHGwQJI0ShQoS3ORdz5nCpA
          description: UserID of the condition owner
        tenantId:
          type: string
          format: uid
          example: 5GI7yWoJk9lvNtuEc66SXCypXVfhbVeH
          description: The tenant id
        dataCondition:
          $ref: '#/components/schemas/DataCondition'
        compoundCondition:
          $ref: '#/components/schemas/CompoundCondition'
      description: only one of compoundCondition or dataCondition should be set
    ConditionDimensions_inner:
      type: object
      properties:
        field:
          type: string
          example: Neighborhood
          description: Field referred to the dimension where the selection is made. This may be used to generate deep links.
        title:
          type: string
          example: Neighborhood
          description: Dimension title
        qLibraryId:
          type: string
          example: PgQKNQ
          description: Refers to a dimension stored in the library
    ConditionHeaders:
      type: array
      items:
        type: string
      example:
      - sumnum
      description: List of header labels
    ConditionCreateRequest:
      type: object
      required:
      - type
      properties:
        type:
          enum:
          - compound
          - data
          type: string
          example: compound
          description: Indicates the condition type
        dataCondition:
          $ref: '#/components/schemas/DataConditionCreateRequest'
        compoundCondition:
          $ref: '#/components/schemas/CompoundCondition'
      description: only one of compoundCondition or dataCondition should be set
    ConditionMeasures_inner:
      type: object
      properties:
        title:
          type: string
          example: sumnum
          description: Measure title
        qLibraryId:
          type: string
          example: PgQKNQ
          description: Refers to a measure stored in the library
        qNumFormat:
          type: object
          example:
            qDec: .
            qFmt: '###0'
            qType: I
            qnDec: 0
            qUseThou: 1
          properties: {}
          description: Format of the field
    CompoundCondition:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/CompoundCondition_data'
        conditionBase:
          $ref: '#/components/schemas/ConditionBase'
      description: A condition made up of other conditions
      x-discriminator-value: compound
      x-ms-discriminator-value: compound
    Selections_inner:
      type: object
      properties:
        count:
          type: number
          example: 2
          description: The count
        field:
          type: string
          example: SalesTerritoryCountry
          description: Field name
        selectedSummary:
          type: array
          items:
            type: string
          example: '[ Germany, Australia ]'
          description: Array of selected
    DataCondition:
      type: object
      properties:
        headers:
          $ref: '#/components/schemas/ConditionHeaders'
        history:
          $ref: '#/components/schemas/HistoryProperties'
        measures:
          $ref: '#/components/schemas/ConditionMeasures'
        dimensions:
          $ref: '#/components/schemas/ConditionDimensions'
        selections:
          $ref: '#/components/schemas/Selections'
        conditionBase:
          $ref: '#/components/schemas/ConditionBase'
        conditionData:
          type: object
          example: {}
          properties: {}
          description: List of parameters specific to data condition are available in DCE and will be passed as is to DCE as per the API docs of data-condition-evaluator
      description: A condition based on data within an app
      x-discriminator-value: data
      x-ms-discriminator-value: data
    DataConditionCreateRequest:
      type: object
      properties:
        headers:
          $ref: '#/components/schemas/ConditionHeaders'
        history:
          $ref: '#/components/schemas/HistoryProperties'
        measures:
          $ref: '#/components/schemas/ConditionMeasures'
        dimensions:
          $ref: '#/components/schemas/ConditionDimensions'
        selections:
          $ref: '#/components/schemas/Selections'
        conditionBase:
          $ref: '#/components/schemas/ConditionBase'
        conditionData:
          type: object
          example: {}
          properties: {}
          description: List of parameters specific to data condition are available in DCE and will be passed as is to DCE as per the API docs of data-condition-evaluator
      description: A condition based on data within an app
      x-discriminator-value: data
      x-ms-discriminator-value: data
    Error:
      type: object
      properties:
        code:
          type: string
          readOnly: true
          description: Error code specific to condition manager.
        meta:
          type: object
          properties: {}
        title:
          type: string
          readOnly: true
          description: Error title.
        detail:
          type: string
          readOnly: true
          description: Error cause.
