openapi: 3.2.0
info:
  title: sharing-tasks sharing settings API
  version: ''
servers:
- url: https://{tenant}.{region}.qlikcloud.com
  variables:
    region:
      default: us
      description: The region the tenant is hosted in
    tenant:
      default: your-tenant
      description: Name of the tenant that will be called
tags:
- name: sharing settings
paths:
  /api/v1/sharing-tasks/settings:
    get:
      tags:
      - sharing settings
      summary: Get sharing settings
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SharingSettings'
          description: The sharing settings have been successfully returned
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      description: Retrieves the current settings for sharing tasks, reports, and other related configuration.
      operationId: sharingSettingsGet
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '1'
        limit: 1000
    patch:
      tags:
      - sharing settings
      summary: Update sharing toggle settings
      responses:
        '204':
          description: Sharing settings have been successfully updated.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad request body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      description: Patches the toggle settings for sharing tasks, reports, and other related configuration in the tenant. User must be assigned the `TenantAdmin` role.
      operationId: sharingSettingsPatch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SharingSettingsPatchCompliantList'
        required: true
        description: Request for updating the API settings
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
    put:
      tags:
      - sharing settings
      summary: Update sharing settings
      responses:
        '204':
          description: API settings have been successfully updated.
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Bad request body
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Internal server error.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
          description: Error response.
      description: Updates the settings for sharing tasks, reports, and other related configuration in the tenant. User must be assigned the `TenantAdmin` role.
      operationId: sharingAPISettingsUpload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/APISettingsUpload'
        required: true
        description: Request for updating the API settings
      x-qlik-visibility: public
      x-qlik-stability: stable
      x-qlik-deprecated: false
      x-qlik-tier:
        tier: '2'
        limit: 100
components:
  schemas:
    Error_meta:
      type: object
      properties:
        httpCode:
          type: integer
          readOnly: true
          description: HTTP error code.
    APISettingsUpload:
      type: object
      required:
      - enable-sharing
      properties:
        maxRecipients:
          type: number
          example: 200
          readOnly: true
          description: Maximum number of recipients when creating a sharing task
        enable-sharing:
          type: boolean
          example: true
          description: Whether API endpoints for sharing are enabled
    SharingSettings:
      type: object
      properties:
        tenantId:
          type: string
          example: cgdsAumGmQ6l0Bi7CUKt9V8P_Y9GL0sC
          readOnly: true
          description: These persisted sharing settings are only available for this tenant. Extracted from request JWT.
        maxRecipients:
          type: number
          example: 200
          readOnly: true
          description: Maximum number of recipients when creating a sharing task
        enable-sharing:
          type: boolean
          example: true
          description: Whether API endpoints for sharing are enabled
        reportSubscriptionStatus:
          enum:
          - none
          - enabling
          - disabling
          type: string
          example: disabling
          readOnly: true
          description: This indicates that there is an ongoing operation to either disable or enable the report subscription feature. none means that no such operation is ongoing. enabling/disabling means that system is currently enabling/disabling the feature
        maxSubscriptionRecipients:
          type: integer
          readOnly: true
          description: Max Recipients accepted when creating a new subscription (excluding the owner)
          x-omitempty: true
        enable-report-subscription:
          type: boolean
          example: true
          description: true if report-subscription feature is enabled for this tenant
        reporting-service-license-status:
          enum:
          - enabled
          - disabled
          type: string
          description: Whether the license for the tenant has the reportingService feature enabled.
          x-omitempty: true
        reportSubscriptionStatusChangeTime:
          type: string
          example: '2020-09-02T13:44:33Z'
          readOnly: true
          description: UTC timestamp of the most recent change of reportSubscriptionStatus. If there has not been any such change, this is the timestamp of the initial creation of the record.
    Error:
      type: object
      properties:
        code:
          type: string
          readOnly: true
          description: Error code specific to sharing service.
        meta:
          $ref: '#/components/schemas/Error_meta'
        title:
          type: string
          readOnly: true
          description: Error title.
        detail:
          type: string
          readOnly: true
          description: Error cause.
    Errors:
      type: object
      example:
        errors:
        - code: HTTP-123
          title: short error message
          details: detailed error message
        traceId: 7975401f3954aa47
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
        traceId:
          type: string
    SharingSettingsPatchCompliant:
      type: object
      required:
      - op
      - path
      properties:
        op:
          enum:
          - replace
          type: string
          description: The operation to be performed.
        path:
          enum:
          - /enable-sharing
          - /enable-report-subscription
          type: string
          description: The path for the given resource field to patch.
        value:
          type: object
          properties: {}
          description: The value to be used for this operation.
    SharingSettingsPatchCompliantList:
      type: array
      items:
        $ref: '#/components/schemas/SharingSettingsPatchCompliant'
      example:
      - op: replace
        path: /enable-sharing
        value: true
      - op: replace
        path: /enable-sharing
        value: false
      - op: replace
        path: /enable-report-subscription
        value: true
      - op: replace
        path: /enable-report-subscription
        value: false
      description: A JSON Patch document as defined in https://datatracker.ietf.org/doc/html/rfc6902.
